language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu

    - env: TARGET=thumbv6m-none-eabi
      rust: beta

    - env: TARGET=thumbv7m-none-eabi
      rust: beta

before_install:
  - set -e
  - rustup self update

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - trying
    - staging

notifications:
  email:
    on_success: never
